Preprocessors, Conditional Lines, Better CustomPearl & CustomUnlock Interface
Garrakx/Custom-Regions pull request #139
Opened 2023-03-14 00:35 UTC by Bro748

-Preprocessors are added, though they currently run after player-conditions.
-Conditional Lines are added as a preprocessor, now go in curly braces.
-Conditional lines can use region acronym, 'MSC,' or the modID of an enabled mod.
-CustomPearls and CustomUnlocks now use modification files, as it's less jank than manual implementations.

2023-03-19 19:19 UTC, Garrakx requested changes
Thanks for the work! see my comments inside

2023-03-19 19:19 UTC, Garrakx commented on assets/CustomPearls.txt
are this files automatically copied to the plugins folder?
Don't you think since this files will be always be changed on runtime, it is better to just load them to memory and skip this ones completely?

2023-03-19 19:19 UTC, Garrakx commented on src/ArenaUnlocks/UnlockEnum.cs
If you named the Method with a 2 at the end to maintain the original, you can safely remove it

2023-03-29 16:12 UTC, Bro748 commented on src/ArenaUnlocks/UnlockEnum.cs
Removed

2023-03-29 16:27 UTC, Bro748 commented on assets/CustomPearls.txt
The files are not automatically copied no, I don't really know the appropriate way to do meta stuff like that with VS.

The existence of these files is necessary in order to use the modification file system. Hypothetically it would be possible to mod the ModMerger to generate files completely from nothing, but there are scenarios where the ModMerger runs before code mods are enabled (it happens when enabling mods in Remix; ModMerger runs before restart while code mods are applied after restart,) and because of this there's no good way to do this without doing some really funky stuff and - all of this is simpler by just starting with 2 empty files.

(Although I've been thinking about doing that Funky Stuff anyways, as it'd be nice to use conditional syntax in modification files.)

And I implemented two different systems for custom handling data in memory before this and both were more jank and less powerful and more complex than the already existing modification system, hence why I think it's best to stick with what's already made.

2023-04-16 11:49 UTC, merged